import { pageMetadata, faqJsonLd, breadcrumbJsonLd } from "@/lib/seo";
import { site } from "@/lib/site";
import { getFaqs } from "@/lib/api";
import FaqSection from "@/components/FaqSection";
import html from "@/content/admissions";

export const metadata = pageMetadata("/admissions");

// Content is the original legacy page markup, injected so the site's CSS
// renders it exactly like the live site. Generated by scripts/port-legacy.mjs.
export default async function Page() {
  const faqsData = await getFaqs();
  const admissionsFaqs = faqsData?.admissions || [];

  return (
    <div id="body">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(
            breadcrumbJsonLd([
              { name: "Home", url: `${site.url}/` },
              { name: "Admissions", url: `${site.url}/admissions` },
            ])
          ),
        }}
      />
      <section
        className="content-wrapper main-content clear-fix"
        dangerouslySetInnerHTML={{ __html: html }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd(admissionsFaqs)) }}
      />
      <FaqSection items={admissionsFaqs} />
    </div>
  );
}
