import { pageMetadata } from "@/lib/seo";
import html from "@/content/setu-project";

export const metadata = pageMetadata("/setu-project");

// Content is the original legacy page markup, injected so the site's CSS
// renders it exactly like the live site. Generated by scripts/port-legacy.mjs.
export default function Page() {
  return (
    <div id="body">
      <section
        className="content-wrapper main-content clear-fix"
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  );
}
