import { pageMetadata, feeFaqs, faqJsonLd, breadcrumbJsonLd } from "@/lib/seo";
import { site } from "@/lib/site";
import FaqSection from "@/components/FaqSection";
import html from "@/content/fee-structure";

export const metadata = pageMetadata("/fee-structure");

// Content is the original legacy page markup, injected so the site's CSS
// renders it exactly like the live site. Generated by scripts/port-legacy.mjs.
export default function Page() {
  return (
    <div id="body">
      {/* JSON-LD structured data — kept before the dangerouslySetInnerHTML section
          and before the Client Component boundary so React hydration never has to
          reconcile them against browser-reparsed HTML. */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(
            breadcrumbJsonLd([
              { name: "Home", url: `${site.url}/` },
              { name: "Admissions", url: `${site.url}/admissions` },
              { name: "Fee Structure & Payment", url: `${site.url}/fee-structure` },
            ])
          ),
        }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd(feeFaqs)) }}
      />
      <section
        className="content-wrapper main-content clear-fix"
        dangerouslySetInnerHTML={{ __html: html }}
      />
      <FaqSection items={feeFaqs} />
    </div>
  );
}
