// One-shot porter: pulls the exact content section out of each legacy
// public/*.html page and generates matching Next.js pages that inject that
// original markup inside the same `content-wrapper` section. The legacy CSS
// (loaded globally) then renders each page identically to the live site.
//
// Run from the web/ dir:  node scripts/port-legacy.mjs
import fs from "node:fs";
import path from "node:path";

const WEB = process.cwd();
const PUBLIC = path.resolve(WEB, "..", "public");
const CONTENT_DIR = path.join(WEB, "src", "content");
const APP_DIR = path.join(WEB, "src", "app");

// slug -> legacy source file (static content pages only)
const PAGES = {
  "about-us": "AboutUs.html",
  "school-history": "Schoolhistory.html",
  "about-society": "AboutSociety.html",
  "objective": "Objective.html",
  "mission": "Mission.html",
  "founder": "Founder.html",
  "chairperson": "Chairperson.html",
  "principal": "Principal.html",
  "committee": "Committee.html",
  "staff": "teachingstaff.html",
  "approach": "Approach.html",
  "academic-calendar": "AcademicCalendar.html",
  "co-curricular": "Curricular.html",
  "facilities": "SchoolInfrastructure.html",
  "safety-security": "Security.html",
  "social-consciousness": "SocialConsciouness.html",
  "online-learning": "Pandemic.html",
  "admissions": "AdmissionProcess.html",
  "fee-structure": "FeeStructure.html",
  "school-timing": "SchoolTiming.html",
  "placements": "Placements.html",
  "vacancies": "Vacancies.html",
  "setu-project": "shiv-niketan-setu-project-community-outreach.html",
  "best-preschool-feroz-shah-road": "best-preschool-near-feroz-shah-road.html",
  "results": "result.html",
};

// legacy .html filename (basename) -> new route slug, for link rewriting
const LINK_MAP = {
  "index.html": "/",
  "Welcome.html": "/about-us",
  "AboutUs.html": "/about-us",
  "Schoolhistory.html": "/school-history",
  "AboutSociety.html": "/about-society",
  "Objective.html": "/objective",
  "Mission.html": "/mission",
  "Founder.html": "/founder",
  "Chairperson.html": "/chairperson",
  "Principal.html": "/principal",
  "Committee.html": "/committee",
  "teachingstaff.html": "/staff",
  "Approach.html": "/approach",
  "AcademicCalendar.html": "/academic-calendar",
  "Curricular.html": "/co-curricular",
  "SchoolInfrastructure.html": "/facilities",
  "Security.html": "/safety-security",
  "SocialConsciouness.html": "/social-consciousness",
  "Pandemic.html": "/online-learning",
  "AdmissionProcess.html": "/admissions",
  "AdmissionProcesscc73.html": "/admissions",
  "Registration.html": "/registration",
  "RegisterStudent.html": "/registration",
  "FeeStructure.html": "/fee-structure",
  "SchoolTiming.html": "/school-timing",
  "result.html": "/results",
  "Placements.html": "/placements",
  "shiv-niketan-setu-project-community-outreach.html": "/setu-project",
  "Vacancies.html": "/vacancies",
  "Gallery.html": "/gallery",
  "Gallery535a.html": "/gallery",
  "AnualEvents.html": "/activities",
  "News.html": "/notices",
  "ContactUs.html": "/contact",
  "best-preschool-near-feroz-shah-road.html": "/best-preschool-feroz-shah-road",
};

function extractContent(html) {
  const marker = "content-wrapper main-content";
  const start = html.indexOf(marker);
  if (start === -1) return null;
  const secOpen = html.indexOf(">", start) + 1; // after <section ...>
  const footerIdx = html.indexOf("<footer", secOpen);
  let chunk = html.slice(secOpen, footerIdx === -1 ? undefined : footerIdx);
  const lastSec = chunk.lastIndexOf("</section>");
  if (lastSec !== -1) chunk = chunk.slice(0, lastSec);
  return chunk.trim();
}

function clean(html) {
  let out = html;
  // Drop inline <script> blocks — they belong to the legacy jQuery flow.
  out = out.replace(/<script[\s\S]*?<\/script>/gi, "");
  // Rewrite internal .html links to the new routes.
  out = out.replace(/(href=")([^"]+?\.html)((?:#[^"]*)?")/gi, (m, p1, url, p3) => {
    const base = url.split("/").pop();
    const slug = LINK_MAP[base];
    return slug ? `${p1}${slug}${p3.slice(0, -1)}"` : m;
  });
  // Make remaining relative asset URLs absolute (served from /public).
  out = out.replace(/((?:src|href)=")(?!https?:|\/|#|mailto:|tel:|data:)([^"]+)(")/gi,
    (m, p1, url, p3) => `${p1}/${url}${p3}`);
  return out;
}

const pageTemplate = (slug) => `import { pageMetadata } from "@/lib/seo";
import html from "@/content/${slug}";

export const metadata = pageMetadata("/${slug}");

// Content is the original legacy page markup, injected so the site's CSS
// renders it exactly like the live site. Generated by scripts/port-legacy.mjs.
export default function Page() {
  return (
    <div id="body">
      <section
        className="content-wrapper main-content clear-fix"
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  );
}
`;

fs.mkdirSync(CONTENT_DIR, { recursive: true });

let ok = 0;
const missing = [];
for (const [slug, file] of Object.entries(PAGES)) {
  const src = path.join(PUBLIC, file);
  if (!fs.existsSync(src)) { missing.push(`${slug}: no ${file}`); continue; }
  const raw = fs.readFileSync(src, "utf8");
  const content = extractContent(raw);
  if (!content) { missing.push(`${slug}: no content-wrapper in ${file}`); continue; }
  const cleaned = clean(content);

  fs.writeFileSync(path.join(CONTENT_DIR, `${slug}.ts`),
    `// Auto-generated from public/${file} — do not edit by hand.\nexport default ${JSON.stringify(cleaned)};\n`);

  const dir = path.join(APP_DIR, slug);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "page.tsx"), pageTemplate(slug));
  ok++;
  console.log(`ported ${slug.padEnd(32)} <- ${file}  (${cleaned.length} chars)`);
}

console.log(`\nDone: ${ok} pages ported.`);
if (missing.length) console.log("Skipped:\n  " + missing.join("\n  "));
